### PR TITLE
Added unit test and fixed file creating

### PR DESCRIPTION
**Pull request by ghost**
I added unit test and fixed file loading issue

### CODE REVIEW

**Comment by DeBukkIt** [comment]
First of all, thank you very much for your contribution.

May I ask how the _file loading issue_ came to light? In other words, under what circumstances did the problem occur, what were the consequences and how can it be reproduced?

**Comment by ghost** [comment]
The issue was caused by incorrect file recongnition. Program wanted to read 0 byte file which was created eariler.(In my case it was temp file) You can reproduce it by opening empty file.

**Comment by ghost** [comment]
Added package name to classes

**Comment by ghost** [comment]
Why no one responds? @DeBukkIt ?

**Comment by DeBukkIt** [comment]
I'm not sure yet how the error manifests itself. For testing, I used a path to a file that doesn't exist. The file is being created automatically and can be used without an error. Shouldn't the error occur at this point or did I misunderstand you?

**Comment by ghost** [comment]
You misunderstanded me. I opened exisitng 
 file with 0 byte content. Then i had error.
Just try opening temp file.

**Comment by DeBukkIt** [comment]
Thanks for pointing that out. I see what you mean now. The bug could easily be fixed by adding a small additional condition in the if branch. This happened with commit #829d46fc5d573da7aae26a4ec05b17ec2abf4369. So that your unit test doesn't have to be taken over, I will not do a merge. Thanks for reporting the bug and your contribution!

**Pull request closed without merging**
